services:
  # PHP-FPM for Laravel
  php:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_api
    volumes:
      - ./backend:/var/www/html
      - ./backend/storage/logs:/var/log/php
    depends_on:
      - postgres
    networks:
      - server_network

  # Nginx for Laravel
  nginx_backend:
    image: nginx:alpine
    container_name: backend_web_server
    ports:
      - "80:80" # Laravel served on port 80
    volumes:
      - ./backend:/var/www/html
      - ./backend/nginx:/etc/nginx/conf.d
    depends_on:
      - php
    networks:
      - server_network

  # Nuxt.js Service
  nuxt:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_ui
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
    environment:
      HOST: 0.0.0.0
      PORT: 3000
    networks:
      - server_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 60s
      timeout: 10s
      retries: 3

  # PostgreSQL Database
  postgres:
    image: postgres:15
    restart: always
    container_name: pg_database
    environment:
      POSTGRES_USER: dev_
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: blog_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - server_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev_"]
      interval: 60s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  server_network:
